# Generated by Django 4.2.6 on 2023-11-29 23:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import docflow.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d', validators=[docflow.validators.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='StudyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docflow.studylevel')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_passport', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('student_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('student_group_number', models.CharField(blank=True, max_length=50, null=True)),
                ('last_change_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('comments', models.ManyToManyField(blank=True, to='docflow.comment')),
                ('current_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docflow.department')),
                ('documents', models.ManyToManyField(blank=True, to='docflow.document')),
                ('last_change_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docflow.course')),
            ],
        ),
    ]
