# Generated by Django 4.2.6 on 2023-11-18 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='last_redacted_user',
            new_name='last_change_user',
        ),
        migrations.RemoveField(
            model_name='application',
            name='last_redacted',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='application',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='application',
            name='last_change_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
