# Generated by Django 4.2.6 on 2023-11-29 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='last_change_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docflow.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docflow.userprofile'),
        ),
    ]
