# Generated by Django 4.2.6 on 2023-11-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0002_rename_last_redacted_user_application_last_change_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('alias', models.CharField(max_length=60)),
            ],
        ),
    ]
