# Generated by Django 4.2.6 on 2023-11-30 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0004_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='current_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docflow.department'),
        ),
    ]
