# Generated by Django 4.2.6 on 2023-11-26 20:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import docflow.validators


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0005_rename_current_department_id_application_current_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docflow.comment'),
        ),
        migrations.AlterField(
            model_name='application',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docflow.document'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student_passport',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/%Y/%m/%d', validators=[docflow.validators.validate_file_extension]),
        ),
    ]
