# Generated by Django 4.2.6 on 2023-11-27 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docflow', '0006_alter_application_comment_alter_application_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='last_change_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='student_group_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
