# Generated by Django 4.2.6 on 2023-11-30 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0007_alter_application_current_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='current_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docflow.department'),
        ),
    ]
