# Generated by Django 4.2.6 on 2023-11-27 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0007_alter_application_last_change_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
