# Generated by Django 4.2.6 on 2023-11-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0010_alter_application_current_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='documents',
            field=models.ManyToManyField(to='docflow.document'),
        ),
    ]
