# Generated by Django 4.2.6 on 2023-11-28 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docflow', '0015_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='application',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='application',
            name='document',
        ),
        migrations.AddField(
            model_name='comment',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docflow.application'),
        ),
        migrations.AddField(
            model_name='document',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docflow.application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_change_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
