# Generated by Django 4.2.6 on 2023-11-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0017_file_documenttest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='application',
        ),
        migrations.RemoveField(
            model_name='document',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='comments',
            field=models.ManyToManyField(to='docflow.comment'),
        ),
        migrations.AddField(
            model_name='application',
            name='documents',
            field=models.ManyToManyField(to='docflow.document'),
        ),
        migrations.DeleteModel(
            name='DocumentTest',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
