# Generated by Django 4.2.6 on 2023-11-28 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docflow', '0018_remove_comment_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='comments',
            field=models.ManyToManyField(blank=True, to='docflow.comment'),
        ),
        migrations.AlterField(
            model_name='application',
            name='documents',
            field=models.ManyToManyField(blank=True, to='docflow.document'),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_change_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
