# Generated by Django 4.2.6 on 2023-11-28 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docflow', '0020_alter_application_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='last_change_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
