# Generated by Django 4.2.6 on 2023-11-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0021_alter_application_last_change_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertest',
            old_name='mail',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='level',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
