# Generated by Django 4.2.6 on 2023-11-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0023_alter_usertest_email_alter_usertest_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docflow.studylevel')),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='student_education_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docflow.studylevel'),
        ),
        migrations.DeleteModel(
            name='EducationLevel',
        ),
    ]
