# Generated by Django 4.2.6 on 2023-11-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0025_alter_application_student_education_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='course_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
