# Generated by Django 4.2.6 on 2023-11-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0026_remove_course_name_course_course_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_number',
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
