# Generated by Django 4.2.6 on 2023-11-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0027_remove_course_course_number_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.SmallIntegerField(),
        ),
    ]
