# Generated by Django 4.2.6 on 2023-11-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0028_alter_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_number',
        ),
    ]
