# Generated by Django 4.2.6 on 2023-11-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0029_rename_name_course_course_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='level',
            new_name='study_level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_number',
        ),
        migrations.AddField(
            model_name='course',
            name='level_number',
            field=models.IntegerField(choices=[], default=1),
            preserve_default=False,
        ),
    ]
