# Generated by Django 4.2.6 on 2023-11-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0033_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='study_level',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.AlterField(
            model_name='application',
            name='student_education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docflow.studylevel'),
        ),
        migrations.AlterField(
            model_name='studylevel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
