# Generated by Django 4.2.6 on 2023-11-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0035_studylevel_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudyLevel',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='student_education_level',
            new_name='student_course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='course_number',
        ),
    ]
