# Generated by Django 4.2.6 on 2023-11-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0036_rename_studylevel_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_number',
            new_name='number',
        ),
    ]
