# Generated by Django 4.2.6 on 2023-11-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0039_alter_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
    ]
